set_property SRC_FILE_INFO {cfile:D:/zonghekechensheji/fingerprint_sensor/fingerprint_sensor.srcs/constrs_1/new/fps.xdc rfile:../../../fingerprint_sensor.srcs/constrs_1/new/fps.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V4 [get_ports {led_tri_o[0]}]
set_property src_info {type:XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U6 [get_ports {led_tri_o[1]}]
set_property src_info {type:XDC file:1 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCATION Y21 [get_bd_pins /processing_system7_0/UART0_RX]
set_property src_info {type:XDC file:1 line:9 export:INPUT save:INPUT read:READ} [current_design]
set_property LOCATION Y20 [get_bd_pins /processing_system7_0/UART0_TX]
