set_property SRC_FILE_INFO {cfile:C:/Users/MikanseiP/Desktop/zonghekechengsheji/us_with_pir/us_with_pir.srcs/constrs_1/new/us_with_pir.xdc rfile:../../../us_with_pir.srcs/constrs_1/new/us_with_pir.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  W21 [get_ports {ult_tri_io[0]}]
set_property src_info {type:XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V20 [get_ports {pir_tri_i[0]}]
set_property src_info {type:XDC file:1 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V4 [get_ports {led_tri_o[0]}]
set_property src_info {type:XDC file:1 line:10 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U6 [get_ports {led_tri_o[1]}]
